name: Backfill Truth

on:
  workflow_dispatch: {}

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Proper auth: use auth@v2 with credentials_json from the secret
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}

      # ✅ Setup gcloud and install bq component
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'bq'

      - name: Check gcloud / bq
        run: |
          gcloud --version
          bq version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps for backfill
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run backfill (2010 → today)
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          python pipelines/backfill_quick.py
