name: BigQuery Sync

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - "sql/**"
      - "pipelines/**"
  schedule:
    - cron: "0 15 * * *"   # 11:00 ET nightly ingest (15:00 UTC during EST)
    - cron: "0 13 * * 1"   # Monday weekly docs publish

jobs:
  bq-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_JSON }}
          export_default_credentials: true

      - name: Install BigQuery CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk

      - name: Apply DDLs (tables + views) if present
        run: |
          set -e
          if [ -d "sql/ddl" ]; then
            for f in sql/ddl/*.sql; do
              [ -e "$f" ] || continue
              echo "Applying $f"
              bq query --use_legacy_sql=false < "$f"
            done
          fi
          if [ -d "sql/views" ]; then
            for f in sql/views/*.sql; do
              [ -e "$f" ] || continue
              echo "Applying view $f"
              bq query --use_legacy_sql=false < "$f"
            done
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi

      - name: Run daily ingest (idempotent if script missing)
        run: |
          if [ -f "pipelines/ingest_daily.py" ]; then
            python pipelines/ingest_daily.py --project originami-sno-prod --dataset sno
          else
            echo "pipelines/ingest_daily.py not found; skipping"
          fi

      - name: Publish weekly docs (optional)
        if: github.event_name == 'schedule'
        run: |
          if [ -f "tools/build_reports.py" ]; then
            python tools/build_reports.py --outdir docs/
            git config user.name "gha-bot"
            git config user.email "gha-bot@users.noreply.github.com"
            git add docs/ && git commit -m "Publish weekly docs" || echo "No changes"
            git push
          else
            echo "tools/build_reports.py not found; skipping"
          fi
