name: BigQuery Sync

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - "sql/**"
      - "pipelines/**"
  schedule:
    - cron: "0 15 * * *"   # daily 15:00 UTC
    - cron: "0 13 * * 1"   # weekly docs

jobs:
  bq-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_JSON }}
          export_default_credentials: true

      - name: Check/Install bq
        run: |
          gcloud --version
          gcloud components install bq -q || true
          bq version

      - name: Apply DDLs (tables + views)
        run: |
          set -e
          if [ -d "sql/ddl" ]; then
            for f in sql/ddl/*.sql; do
              [ -e "$f" ] || continue
              echo "Applying $f"
              bq query --use_legacy_sql=false < "$f"
            done
          fi
          if [ -d "sql/views" ]; then
            for f in sql/views/*.sql; do
              [ -e "$f" ] || continue
              echo "Applying view $f"
              bq query --use_legacy_sql=false < "$f"
            done
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Backfill original metrics (2010→today)
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          python pipelines/backfill_quick.py
  export-csvs:
    runs-on: ubuntu-latest
    needs: bq-sync
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps just for export
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pandas==2.2.2 numpy==1.26.4 yfinance==0.2.43 lxml==5.3.0

      - name: Build yearly CSVs zip
        run: |
          python pipelines/export_csvs_by_year.py
          ls -l out

      - name: Upload CSVs artifact
        uses: actions/upload-artifact@v4
        with:
          name: ohlcv-yearly-csvs
          path: out/ohlcv_by_year_2010_to_today.zip
          if-no-files-found: error
